### ISSUE TITLE
无法下载游戏

### ISSUE THREAD

**Issue by pedoc** [rwv/chinese-dos-games#100]
**bug 描述**
bug 的描述

脚本运行正常，但是bin目录下什么也没有。通过输出日志发现构建的url被urlencode了，如果直接换成中文名称比如https://dos.zczc.cz/static/games/bin/%E4%BD%9C%E6%88%98%E9%9B%86%E
5%9B%A2.zip -> https://dos.zczc.cz/static/games/bin/作战集团.zip 那么就可以下载（浏览器直接打开被编码URL的也无法下载）

**如何重现**
如何重现这个 bug
python download_data.py
**预期情况**
你预期的正常情况
能够下载游戏文件到bin目录
**截图**
![image](https://user-images.githubusercontent.com/6604230/51784568-b7d3f880-2185-11e9-8d0f-8e548b60c51d.png)

**系统环境**
操作系统：
windows10 x64
浏览器：
chrome 73
游戏：
all

**Comment by pedoc** [comment]
参照python代码写了一个C#实现
https://github.com/pedoc/chinese-dos-games

**Comment by rwv** [comment]
Chrome 71.0.3578.98 (Official Build) (64-bit) 及 Safari Version 12.0.2 (14606.3.4) 可以正常下载 `https://dos.zczc.cz/static/games/bin/%E4%BD%9C%E6%88%98%E9%9B%86%E5%9B%A2.zip`

**Comment by rwv** [comment]
运行这个脚本大约消耗了多久时间呢

**Comment by pedoc** [comment]
我chrome版本是：
73.0.3679.0（正式版本） （64 位）

最开始我是没限制并发数，然后服务器会因为连接数太多拒绝连接，所以后来限制为10路并发下载。我这边是100M带宽，下行稳定在9-10m/s，我没全部把文件下载完成，所以没有评估整个的运行时长。

猜测应该不是浏览器的问题，我换过firefox也不行。可能还是系统关系，我是最新的1809。如果单独使用wget下载也是不行的，需要加上 --no-verify-ssl 参数，还是证书问题

**Comment by rwv** [comment]
有没有可能是系统编码的问题？身边现在没有 Windows 环境。

**Comment by FlandreDot** [comment]
是证书的问题，我在win10 20h2的版本，用了chrome和firefox也都会出现转码的情况，但是不管是转不转都能下载
然后在跑python的时候发现会抛出_ssl.c:645的错误！！

于是我就在download_data.py里面加上了下面的代码忽略证书错误就可以正常下载了：

> import ssl
>  
> ssl._create_default_https_context = ssl._create_unverified_context

**Comment by FlandreDot** [comment]
> 有没有可能是系统编码的问题？身边现在没有 Windows 环境。

是证书的问题，然后跑完整个脚本花了37分钟左右，公司的网络我也不知道多少带宽XD
