### ISSUE TITLE
江湖任我行 无法进入游戏

### ISSUE THREAD

**Issue by WindforceYang** [rwv/chinese-dos-games#101]
**bug 描述**
加载完游戏后一直停留在黑屏状态。
鼠标点击、键盘输入均没有反应。

**如何重现**
进入https://dos.zczc.cz/games/%E6%B1%9F%E6%B9%96%E4%BB%BB%E6%88%91%E8%A1%8C/页面
Launch game file
进入系统启动游戏的画面
黑屏

**预期情况**
正常进入游戏

**截图**
bug 的截图
![image](https://user-images.githubusercontent.com/30133546/51788074-d5826d00-2147-11e9-9e47-4c82438bfbb5.png)

**系统环境**
操作系统：Windows10 64-bit
浏览器：Chrome Version 71.0.3578.98 (Official Build) (64-bit)
游戏：江湖任我行https://dos.zczc.cz/games/%E6%B1%9F%E6%B9%96%E4%BB%BB%E6%88%91%E8%A1%8C/

**Comment by rwv** [comment]
无法重现
