### ISSUE TITLE
是否有可能讀取client電腦的遊戲, 或者新增API去讀取外部DOS遊戲?

### ISSUE THREAD

**Issue by wonson** [rwv/chinese-dos-games#105]
**要求的功能**
描述功能
讀取client電腦的遊戲, 或者新增API去讀取外部(網盤/gd之類)DOS遊戲?

**优先度**
* [ ] 高
* [ ] 中
* [ ] 低

鋻於遊戲有侵權問題, 會否增加將遊戲可能外部載入的方法? 
畢竟遊戲雖然存在版權問題, 但模擬器本身的開發和開發的辛勞是無罪的

如果有外部載入的API, 玩家社群之間亦可以自己尋求方法去分享, 保存和運行遊戲.

**Comment by rwv** [comment]
https://dos.zczc.cz/games/custom/ 现在提供了读取外部游戏的功能，但此功能还不完善。

**Comment by rwv** [comment]
closed
