### ISSUE TITLE
网页上能否加个虚拟键盘，这样子手机上也可以玩了哈！

### ISSUE THREAD

**Issue by agamem** [rwv/chinese-dos-games#11]
**要求的功能**
网页上能否加个虚拟键盘，这样子手机上也可以玩了哈！

**优先度**
* [ ] 高
* [x] 中
* [ ] 低

**Comment by rwv** [comment]
发现有点困难，目前不会去考虑添加虚拟键盘

**Comment by watermoonchandra** [comment]
是不是可以调用系统的输入法来解决手机键盘问题？我在手机上配合DosBox安装了一个GamePad应用，可以作为系统的输入法来调用虚拟手柄，玩起来很不错，甚至像《大航海时代2》这样的鼠标游戏都能够用手柄来玩。

**Comment by rwv** [comment]
https://stackoverflow.com/questions/14349449/how-to-add-on-screen-virtual-keyboard-to-a-html5-javascript-canvas-mobile-game

**Comment by rwv** [comment]
似乎 Puffin Browser 有可以模拟键鼠的功能

**Comment by rwv** [comment]
added
