### ISSUE TITLE
轉校生無法運行

### ISSUE THREAD

**Issue by gavinliao1124** [rwv/chinese-dos-games#112]
**bug 描述**
bug 的描述

**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：
浏览器：
游戏：

**Comment by gavinliao1124** [comment]
![image](https://user-images.githubusercontent.com/48398813/54080333-482a5f00-4328-11e9-9260-67ce96638056.png)

**Comment by rwv** [comment]
fixed
