### ISSUE TITLE
仙剑加载不出来

### ISSUE THREAD

**Issue by Dawnlord** [rwv/chinese-dos-games#114]
**bug 描述**
bug 的描述
仙剑加载不出来
停在dos界面

**如何重现**
如何重现这个 bug
启动游戏

**预期情况**
你预期的正常情况
正常加载游戏

**截图**
bug 的截图
![image](https://user-images.githubusercontent.com/10655859/54169965-cebd7880-44af-11e9-8f65-453778c5541d.png)

**系统环境**
操作系统：win10
浏览器：Chrome
游戏：仙剑

**Comment by Dawnlord** [comment]
手动输入PAL!.exe 解决问题

**Comment by crstudio** [comment]
刷新一下， 不要用鼠标点击，用键盘

**Comment by rwv** [comment]
清理一下缓存？
