### ISSUE TITLE
请求添加小小探险家奥斯卡

### ISSUE THREAD

**Issue by balloonistlover** [rwv/chinese-dos-games#119]
**游戏简体中文名：** 小小探险家奥斯卡农场奇遇记
**游戏繁体中文名：**小小探險家奧斯卡農場奇遇記
**游戏英文名：**Oscar the Balloonist Discovers the Farm
**游戏发行年份：**2001
**游戏下载地址（可选）：**http://legendsworld.net/adventure/game/8982
**游戏封面图地址（可选）：**https://www.amazon.co.uk/Tivola-Oscar-Balloonist-Discovers-Farm/dp/B00004U26U
**其他（如键位、秘籍、链接等等）（可选）：**

**Comment by rwv** [comment]
这似乎不是一个DOS游戏？
