### ISSUE TITLE
dos 直接暴露会不会危险

### ISSUE THREAD

**Issue by caojiantao** [rwv/chinese-dos-games#123]
![image](https://user-images.githubusercontent.com/10186147/57145834-9d4d9300-6df6-11e9-8cf4-06979dd0ef6a.png)

**Comment by journey-ad** [comment]
这里的DOS是模拟器模拟出来的，运行在浏览器上，每个人看到的都是不同的环境

**Comment by zdsiyan** [comment]
这是个js模拟出来的dos吧

**Comment by Abandon5741** [comment]
相当于一个虚拟机，还是运行在浏览器上的，能有什么危险。

**Comment by KuRRe8** [comment]
是DOSBOX啊
