### ISSUE TITLE
手机端键盘支持

### ISSUE THREAD

**Issue by rainssong** [rwv/chinese-dos-games#127]
手机浏览器可以正常加载游戏，但是没有键盘，无法正常游戏。

建议：
允许自定义虚拟按键，根据需求将按键添加到屏幕上。

**Comment by waylonwang** [comment]
没有键盘甚至连游戏都无法正常进入，例如三国志英杰传第一个界面输入密码就无法继续

**Comment by allentranks** [comment]
确实。如果可以解决手机上的按键问题，那就完美了：）
