### ISSUE TITLE
Macbook最新版系统 没有声音

### ISSUE THREAD

**Issue by mark1188-ui** [rwv/chinese-dos-games#149]
试了好几个游戏，我的macbook都没有声音

**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：
浏览器：
游戏：

**Comment by Peng851026** [comment]
同问

**Comment by myweet** [comment]
是不是在safair下玩的？因为苹果浏览器默认屏蔽声音的。所以只需要改一下默认播放声音就可以了。我之前也以为没声音后来发才现是浏览器的问题 。
