### ISSUE TITLE
Firefox 无法运行

### ISSUE THREAD

**Issue by rwv** [rwv/chinese-dos-games#15]
**bug 描述**
Firefox 无法运行

**截图**
![console](https://user-images.githubusercontent.com/7891383/45107424-216a5080-b16c-11e8-8c64-130fa2f2489d.png)

**系统环境**
操作系统：Win7
浏览器：Firefox

**Comment by rwv** [comment]
无法在 Firefox 61.0.2 (64-bit) / macOS 10.13.5 (17F77) 上复现

**Comment by rwv** [comment]
已知问题 Firefox 版本: 43.0.3

**Comment by rarpainting** [comment]
firfox 支持 wasm 的最低版本是 52 , 看 [这里](https://caniuse.com/#search=wasm)

**Comment by rarpainting** [comment]
> 已知问题 Firefox 版本: 43.0.3

firfox 支持 wasm 的最低版本是 52 , 看 [这里](https://caniuse.com/#search=wasm)
