### ISSUE TITLE
古文明霸王傳 無法遊玩

### ISSUE THREAD

**Issue by sa86c15** [rwv/chinese-dos-games#152]
bug 描述
《古文明霸王传》打不開，提示找不到光碟

如何重現
正常打開就能看到

預期情况
正常進入遊戲

截图
![image](https://user-images.githubusercontent.com/18672503/78955700-98b75180-7b12-11ea-981e-5056b6e5c60a.png)

系统環境
操作系统：macOS Catalina 版本 10.15.4
瀏覽器：Google chrome 版本 81.0.4044.92 (正式版本) (64 位元)
遊戲：《古文明霸王傳》

**Comment by rwv** [comment]
fixed
