### ISSUE TITLE
麻烦看下：iPad配Magic Mouse无法激活鼠标

### ISSUE THREAD

**Issue by flamyelf** [rwv/chinese-dos-games#158]
测试游戏：三国志英杰传
设备：iPad Pro 2018 @iOS14 DP1、Magic Mouse2
Safari、Chrome、Firefox三个浏览器都试过，折叠键盘可以按回车越过“密码”，但随后的菜单无法使用鼠标选择

辛苦看下哈，非常感谢

**Comment by rwv** [comment]
新引擎可以使用触摸
