### ISSUE TITLE
Chrome 全屏卡死

### ISSUE THREAD

**Issue by rwv** [rwv/chinese-dos-games#16]
**bug 描述**
1. "全屏游戏"之后，会出现闪屏，之后 stuck, 游戏不能继续
2. 1出现后，刷新页面，游戏重新开始，之前存储的进度均已丢失

**如何重现**
多次全屏

**系统环境**
操作系统：macOS 10.13.5
浏览器：Chrome 68.0.3440.106 (Official Build) (64-bit)
游戏：仙剑

**Comment by rwv** [comment]
在 Safari Version 11.1.1 (13605.2.8) 无法复现，Chrome 68.0.3440.106 (Official Build) (64-bit)上可以复现但无法稳定复现。

**Comment by rwv** [comment]
测试后，不止仙剑卡死，包括其他游戏。

**Comment by ImHUan** [comment]
Mac 10.13.6
Chrome 69.0.3497.92
遇到相同问题，烦请开发者fix，谢谢！
