### ISSUE TITLE
超時空英雄傳說不能玩

### ISSUE THREAD

**Issue by molesu** [rwv/chinese-dos-games#160]
**bug 描述**
cdrom initialize error

**如何重现**
執行GAME 就會出現

**预期情况**
我想可以玩

**截图**
bug 的截图
![image](https://user-images.githubusercontent.com/67702972/86267205-f383b500-bbf8-11ea-92a9-c5cb3d6a13b5.png)

**系统环境**
操作系统：win10
浏览器：Chrome
游戏：
![image](https://user-images.githubusercontent.com/67702972/86267247-01d1d100-bbf9-11ea-86a8-f77c91f3b7dc.png)

thanks>.<

**Comment by rwv** [comment]
fixed. https://dos.zczc.cz/games/%E8%B6%85%E6%97%B6%E7%A9%BA%E8%8B%B1%E9%9B%84%E4%BC%A0%E8%AF%B4/
