### ISSUE TITLE
吞食天地4

### ISSUE THREAD

**Issue by brianHaoxiang** [rwv/chinese-dos-games#162]
吞食天地4 玩不了

**Comment by candyman0618** [comment]
![@不合格](https://user-images.githubusercontent.com/25203379/100652542-0b1ac180-3382-11eb-8507-0d5994e2a411.jpg)
NO DATA

**Comment by rwv** [comment]
fixed https://dos.zczc.cz/games/%E5%90%9E%E9%A3%9F%E5%A4%A9%E5%9C%B04/
