### ISSUE TITLE
剑侠情缘 和 绝代双骄不能玩

### ISSUE THREAD

**Issue by shuyingz** [rwv/chinese-dos-games#164]
RT

紫薯紫薯紫薯

**Comment by rwv** [comment]
绝代双骄 fixed. 
![image](https://user-images.githubusercontent.com/7891383/147730791-fdb9e31a-1ece-4019-b471-8df271c740ae.png)

**Comment by rwv** [comment]
剑侠情缘 参见 https://github.com/rwv/chinese-dos-games/issues/211
