### ISSUE TITLE
足球小子无法运行

### ISSUE THREAD

**Issue by stargazer1sdh** [rwv/chinese-dos-games#169]
**bug 描述**
![image](https://user-images.githubusercontent.com/24764272/103153749-ad856380-47cd-11eb-9703-b28fcab72979.png)

**如何重现**
直接加载

**预期情况**
正常加载

**系统环境**
操作系统：win10
浏览器：chrome
游戏：足球小子

**Comment by rwv** [comment]
解决. 需要 `ems=false`
https://dos.zczc.cz/games/%E8%B6%B3%E7%90%83%E5%B0%8F%E5%AD%90/
