### ISSUE TITLE
新游戏: 梦幻模拟战2

### ISSUE THREAD

**Issue by zecui** [rwv/chinese-dos-games#17]
**游戏简体中文名：** 梦幻模拟战2
**游戏繁体中文名：** 梦幻模拟战2
**游戏英文名：** Langrisser II
**游戏发行年份：** 1994
**游戏下载地址（可选）：**
**游戏封面图地址（可选）：**
**其他（如键位、秘籍、链接等等）（可选）：**

**Comment by rwv** [comment]
梦幻模拟战2为 MD 平台游戏，而非 DOS 平台游戏，无法添加，抱歉了。
