### ISSUE TITLE
win环境无法下载

### ISSUE THREAD

**Issue by Svenmax** [rwv/chinese-dos-games#171]
**bug 描述**
感谢大佬的项目，刚才在win环境下载，在bin目录里没有游戏文件，请问怎么解决？
还有就是默认的5000端口在哪里修改?
感谢。

**如何重现**
win7 64+python3.8

**预期情况**

**截图**
<img width="747" alt="bin" src="https://user-images.githubusercontent.com/77367951/104476082-caf26400-55fa-11eb-8395-4bad98171869.png">

**系统环境**
操作系统：win7 64
浏览器：Chrome
游戏：all

**Comment by Svenmax** [comment]
https://wolfavenue.lanzoux.com/iWG65kdkh9e

**Comment by zkkzkk32312** [comment]
> https://wolfavenue.lanzoux.com/iWG65kdkh9e
> 
> 有相同问题的朋友请使用这个软件
> 来自
> https://github.com/pedoc/chinese-dos-games

chinese-dos-games.exe 運行無反應
download_data.py 運行後沒有下載

**Comment by Svenmax** [comment]
> > https://wolfavenue.lanzoux.com/iWG65kdkh9e
> > 有相同问题的朋友请使用这个软件
> > 来自
> > https://github.com/pedoc/chinese-dos-games
> 
> chinese-dos-games.exe 運行無反應
> download_data.py 運行後沒有下載

请使用我在蓝奏云分享的那个下载软件。

**Comment by zkkzkk32312** [comment]
> chinese-dos-games.exe



> > > https://wolfavenue.lanzoux.com/iWG65kdkh9e
> > > 有相同问题的朋友请使用这个软件
> > > 来自
> > > https://github.com/pedoc/chinese-dos-games
> > 
> > 
> > chinese-dos-games.exe 運行無反應
> > download_data.py 運行後沒有下載
> 
> 请使用我在蓝奏云分享的那个下载软件。

chinese-dos-games.exe 就是你分享的那個Release.zip 裡面唯一的執行檔
一打開就自動關掉

**Comment by rwv** [comment]
应该解决了，之前的 binary 的地址挂掉了。
5000 端口请修改 `app.py` 的
```
    app.run(debug=True)
```
为
```
    app.run(debug=True, port=80)
```
