### ISSUE TITLE
CHROME53.0.2785.89不能运行游戏

### ISSUE THREAD

**Issue by qdtroubleboy** [rwv/chinese-dos-games#174]
**bug 描述**
bug 的描述
CHROME 53.0.2785.89浏览器，无法运行游戏，似乎是扩展的程序没有运行，手动输入命令都是提示内存不足
**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：
浏览器：
游戏：

**Comment by inyourface34456** [comment]
use the latest version of chrome, witch if i understand right, is available in china
