### ISSUE TITLE
大富翁3存档导出之后再导入存档发现存档丢失

### ISSUE THREAD

**Issue by ItoYuukirin** [rwv/chinese-dos-games#180]
**bug 描述**
bug 的描述：
玩大富翁3，我导入的时候自动重启了游戏，没有出现该有的存档

**如何重现**
如何重现这个 bug：
网页右下角导出存档，导入存档

**预期情况**
你预期的正常情况：
出现该有的存档

**截图**
bug 的截图

**系统环境**
操作系统：
浏览器：
游戏：

**Comment by ksws0281099** [comment]
嗯。导入导出存档似乎不太好使呢

**Comment by rwv** [comment]
问题已解决，问题的原因是在 dosbox 运行时，Indexeddb 加了锁因此没法删除。之前的导出存档是没问题的，导入有问题，可以直接使用直接导出的存档。
