### ISSUE TITLE
龙骑士3的进入问题

### ISSUE THREAD

**Issue by tangxiaodie** [rwv/chinese-dos-games#182]
**bug 描述**
进入游戏的时候，一直提示“请将龙骑士III的光碟片，放进A:槽并按任意键！”

解决办法：
　　我以前玩的时候遇到过，这个问题的解决办法是把龙骑士3所在的目录，映射到A:就可以正常运行了，Dos命令里可以用subst a: c:\dra3映射过去。　　
　　或者您也可以使用mount命令再映射的a:

**Comment by rwv** [comment]
thank you! fixed.
