### ISSUE TITLE
请问如何讲导出的存档JSON还原为普通存档文件？

### ISSUE THREAD

**Issue by uzar1091** [rwv/chinese-dos-games#183]
**要求的功能**
是否将JSON内的base64字符串还原为byte即可？

**优先度**
* [ ] 高
* [ ] 中
* [x] 低

**Comment by rwv** [comment]
base64 字符串会还原成 Array Buffer 的形式。但是具体的 Array Buffer 和文件的匹配关系需要查阅 [emularity](https://github.com/db48x/emularity) 的实现方式。
