### ISSUE TITLE
紅色警戒無法運行

### ISSUE THREAD

**Issue by tommy9453** [rwv/chinese-dos-games#184]
**bug 描述**
bug 的描述:打開後出現類似BIOS的藍屏顯示

**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况:打開後遊戲就能正常運行

**截图**
bug 的截图
![image](https://user-images.githubusercontent.com/61874610/120157750-eb2b6400-c225-11eb-81b9-b56a9a951b7f.png)

**系统环境**
操作系统：windows 10
浏览器：google
游戏：紅色警戒

**Comment by guo-weijie** [comment]
edge也有这个问题

**Comment by hubobj** [comment]
我也同样出现了这个问题

**Comment by rwv** [comment]
fixed
