### ISSUE TITLE
win docker 创建好，将下载得文件放到哪个目录？？

### ISSUE THREAD

**Issue by owl-lwo** [rwv/chinese-dos-games#185]
**要求的功能**
描述功能
windows系统 docker部署， 创建好，点击游戏自动下载游戏文件，请问将下载得文件放到哪个目录？？
**优先度**
* [ ] 高
* [ ] 中
* [ ] 低

**Comment by rwv** [comment]
目前是不提供 Docker 支持的，另外下载的文件是放在 `bin` 目录下面的。
