### ISSUE TITLE
游戏无法下载了 bin目录是空的

### ISSUE THREAD

**Issue by nickdanes** [rwv/chinese-dos-games#193]
游戏无法下载了 bin目录是空的

**Comment by rwv** [comment]
刚才服务 down 了 4 分钟，现在应该恢复正常了。
时间从 2021-08-06 07:15:51 UTC+0 到 2021-08-06 07:20:44 UTC+0。

**Comment by nickdanes** [comment]
> 刚才服务 down 了 4 分钟，现在应该恢复正常了。
> 时间从 2021-08-06 07:15:51 UTC+0 到 2021-08-06 07:20:44 UTC+0。

还是不可以下载呢
![1628238614(1)](https://user-images.githubusercontent.com/13747155/128481622-cc3f1777-7b5b-48eb-8c06-5147b260d05f.png)
这样很快就刷过了。。。bin目录是空的

**Comment by rwv** [comment]
https://github.com/rwv/chinese-dos-games/pull/192/commits/7a9862e72110fa8f498e0889d8069a20819fbbe8

您要不试试这个？

**Comment by nickdanes** [comment]
> [7a9862e](https://github.com/rwv/chinese-dos-games/commit/7a9862e72110fa8f498e0889d8069a20819fbbe8)
> 
> 您要不试试这个？

这个好像可以下在了
