### ISSUE TITLE
金庸群侠传的进度如何保存，

### ISSUE THREAD

**Issue by newgamezhang** [rwv/chinese-dos-games#195]
**要求的功能**
描述功能
如何能在1台电脑中游戏，然后在另外一台电脑中继续上上一台电脑中保存的进度，昨天测试了一下，在chrome中保存的进度，换了edge浏览器，就无法读取刚刚保存的进度，这个应该如果操作呢
**优先度**
* [ ] 高
* [ ] 中
* [ ] 低

**Comment by rwv** [comment]
无法复现这个问题，您方便把存档文件上传上来吗？
