### ISSUE TITLE
马场大亨这个游戏玩不了，没法直接玩

### ISSUE THREAD

**Issue by Would-like** [rwv/chinese-dos-games#196]
**bug 描述**
网址是这个
https://dos.zczc.cz/games/%E9%A9%AC%E5%9C%BA%E5%A4%A7%E4%BA%A8/
打开点击然后显示Not enough 3000k EMS or XMS

**如何重现**
每次都这样

**截图**
bug 的截图
![图片](https://user-images.githubusercontent.com/68805482/130176273-fc7368ca-17cf-4f0e-b6b9-81f761571d56.png)

**系统环境**
操作系统：win7旗舰和win10企业 64位
浏览器：Firefox 64位
游戏：马场大亨

**Comment by rwv** [comment]
fixed
