### ISSUE TITLE
疯狗无法正常游戏

### ISSUE THREAD

**Issue by ccb3275** [rwv/chinese-dos-games#199]
**bug 描述**
https://dos.zczc.cz/games/%E7%96%AF%E7%8B%97/
进入游戏时提示：
Directory .\maddog doesn't exist.
Illegal command: c:\maddog\maddog.exe

**如何重现**
打开游戏即出现

**临时解决办法**
在DOSBOX窗口输入
mount d /emulator/c -t cdrom
maddog.exe
可正常游戏

**Comment by rwv** [comment]
fixed
