### ISSUE TITLE
Feature request:游戏网页全屏（类似视频网站那种）

### ISSUE THREAD

**Issue by hye** [rwv/chinese-dos-games#2]
**要求的功能**
游戏网页全屏（类似视频网站那种）, 因为html内置的全屏api，chrome在全屏时会占用`ESC`键 导致需要按esc的时候退出全屏

**Comment by rwv** [comment]
类似视频网站那种？请问能不能给个例子呢

**Comment by hye** [comment]
https://v.qq.com 随便点个视频  播放器控件 右边数第2个
