### ISSUE TITLE
请求加上《天地劫：神魔至尊传》

### ISSUE THREAD

**Issue by DanielWuY** [rwv/chinese-dos-games#20]
**游戏简体中文名：天地劫：神魔至尊传** 
**游戏发行年份：1999**

**Comment by rwv** [comment]
你好，这个游戏我找不到DOS版本的文件，能提供链接吗？

**Comment by flypart** [comment]
这个游戏虽然画质是dos（320*240分辨率）的，但是实际上是win的呀

**Comment by rwv** [comment]
由于不是 DOS 游戏，Close issue.
