### ISSUE TITLE
關於無聲狂蕭

### ISSUE THREAD

**Issue by cnk456** [rwv/chinese-dos-games#200]
**bug 描述**
網站遊戲無法正常開啟，即使下載後再使用啟動命令無法開啟遊戲。疑似檔案有不明原因無法運作!

**如何重现**
網頁遊戲介面為指令自動跑完的情況下，無法正常開啟遊戲!
如是在下載遊戲後，自行輸入指令(有 依照網頁資訊打入正確指令)後仍會出現與網頁的情況一樣，無法開啟遊戲!

**预期情况**
你预期的正常情况

**截图**
![00](https://user-images.githubusercontent.com/90097608/132095356-cfdc2952-81d2-4b29-88a2-78b91ef6a985.gif)
![未命名](https://user-images.githubusercontent.com/90097608/132095358-46b7995b-1c4e-4f33-aec1-17f9d8b3086a.gif)

**系统环境**
操作系统：為該網站上的DOSBox-0.74-3
浏览器：windows系列
游戏：無聲狂嘯

因為很想要玩到早期經典遊戲，有自行上網爬很多:文終於找到有可能是中文版的無聲狂嘯。希望可以幫幫忙修理遊戲!十分感謝!

**Comment by rwv** [comment]
fixed
