### ISSUE TITLE
英雄无敌2中文版 虚拟光驱加载失败

### ISSUE THREAD

**Issue by BoKoIsMe** [rwv/chinese-dos-games#204]
**bug 描述**
英雄无敌2中文版 虚拟光驱加载失败

**如何重现**
打开游戏虚拟光驱未挂载

**预期情况**
正常挂载虚拟光驱

**截图**
![15](https://user-images.githubusercontent.com/22574116/132507059-ce598b83-2d2f-47f5-8c1a-c9142c2c6c77.png)
![16](https://user-images.githubusercontent.com/22574116/132507064-0cdb6227-1ebf-469c-a29a-9f40a4d9637d.png)

**系统环境**
操作系统：Windows10
浏览器：new edge
游戏：《魔法门:英雄无敌2中文版》

**Comment by rwv** [comment]
fixed

**Comment by BoKoIsMe** [comment]
> fixed

网站还是加载不了CD

**Comment by rwv** [comment]
![image](https://user-images.githubusercontent.com/7891383/148711901-065cd7a7-1611-4df5-a2ad-572bf220c495.png)

**Comment by rwv** [comment]
我这没问题啊

**Comment by xaxiao** [comment]
edge里可以的，chrome里面不行，不过chrome我以前加载过，不知道是不是缓存问题
