### ISSUE TITLE
<阿貓阿狗>無法遊玩

### ISSUE THREAD

**Issue by pimp1234** [rwv/chinese-dos-games#207]
**bug 描述**
在網路遊玩會黑屏（用chrome），在magic dosbox下遊玩只能看到軟星的logo就彈出

**如何重现**
PC用瀏覽器遊玩，android平板用dosbox遊玩

**预期情况**
可以順利遊玩

**截图**
bug 的截图

**系统环境**
操作系统：PC & android labtop
浏览器：chrome & firefox
游戏：阿貓阿狗

**Comment by rwv** [comment]
![image](https://user-images.githubusercontent.com/7891383/135419611-562d24c9-9a46-446e-a0e1-0f5f83559d2a.png)

无法复现
