### ISSUE TITLE
怎么让存档直接保存在服务端？某位大大做了个docker版

### ISSUE THREAD

**Issue by jhk5263** [rwv/chinese-dos-games#208]
**要求的功能**

某位大大做了个docker版，在群晖上跑着，想着要是能直接把存档保存再群晖上，那任何设备玩的时候都能直接调用到存档了

描述功能

**优先度**
* [ ] 高
* [ ] 中
* [ ] 低

**Comment by rwv** [comment]
存档目前保存在 indexedbb 当中，但目前没有保存在服务端的计划。
