### ISSUE TITLE
天龙八部无法启动

### ISSUE THREAD

**Issue by 524483676** [rwv/chinese-dos-games#210]
**bug 描述**
bug 的描述

**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：mac
浏览器：谷歌浏览器
游戏：天龙八部
https://dos.zczc.cz/games/%E5%A4%A9%E9%BE%99%E5%85%AB%E9%83%A8/

**Comment by rwv** [comment]
fixed
