### ISSUE TITLE
传说纪元黑暗之屋无法存档

### ISSUE THREAD

**Issue by kebiblblblblb** [rwv/chinese-dos-games#212]
**bug 描述**
传说纪元黑暗之屋存档完成后，再读取存档时，存档栏里全是空的。

**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：
浏览器：
游戏：

**Comment by rwv** [comment]
需要在游戏中保存后，再点击控制栏的保存按钮
