### ISSUE TITLE
添加微软娱乐包 1-4

### ISSUE THREAD

**Issue by DevScholar** [rwv/chinese-dos-games#228]
**游戏简体中文名：微软娱乐包**
**游戏繁体中文名：**
**游戏英文名：Microsoft Entertainment Pack**
**游戏发行年份：1990**
**游戏下载地址（可选）：https://winworldpc.com/product/microsoft-entertainm/1**  注：这个游戏包由 4 个部分组成，要下载 4 次。后面的 “Best of”和前面完全重复了，可以不下载。
**游戏封面图地址（可选）：http://www.shopmsdn.com/upload/cover/20160905002608.jpg**
**其他（如键位、秘籍、链接等等）（可选）：这个游戏依赖于 Windows 3.0 或更高版本。这个游戏包由多个部分组成，总和不到 10MB 却包含了 31个游戏。**

**Comment by joanna-lee-0** [comment]
我係一個淫婦，想𨳒我嗎？
