### ISSUE TITLE
运行 python3 download_data.py 无法下载

### ISSUE THREAD

**Issue by zhengmz** [rwv/chinese-dos-games#230]
**bug 描述**
运行 python3 download_data.py 无法下载游戏，bin 目录为空

**如何重现**
直接运行 `python3 download_data.py`

**预期情况**
预期应该根据 games.json 来下载游戏

**截图**

1. 浏览器直接访问 `https://dos-bin.zczc.cz/%E4%B8%89%E5%9B%BD%E8%8B%B1%E6%9D%B0%E4%BC%A0.zip` 时，出现

   ![1666592868950](https://user-images.githubusercontent.com/3997518/197462083-6d4a19be-709b-45cc-8a55-b204b5c3012b.png)

2. 直接在 CentOS7 下使用 wget，也出错
 
   ```
   [user@centos7 ~]$ wget https://dos-bin.zczc.cz/%E5%A4%A7%E8%88%AA%E6%B5%B7%E6%97%B6%E4%BB%A32.zip
   --2022-10-24 16:38:48--  https://dos-bin.zczc.cz/%E5%A4%A7%E8%88%AA%E6%B5%B7%E6%97%B6%E4%BB%A32.zip
   正在解析主机 dos-bin.zczc.cz (dos-bin.zczc.cz)... 172.67.195.174, 104.21.90.52, 2606:4700:3031::ac43:c3ae, ...
   正在连接 dos-bin.zczc.cz (dos-bin.zczc.cz)|172.67.195.174|:443... 已连接。
   已发出 HTTP 请求，正在等待回应... 404 Not Found
   2022-10-24 16:38:50 错误 404：Not Found。
   ```

**系统环境**
操作系统：Win11
浏览器：Microsoft Edge 106.0.1370.52
游戏：

**Comment by rwv** [comment]
fixed

**Comment by zhengmz** [comment]
感谢
