### ISSUE TITLE
新游戏：太阁立志传

### ISSUE THREAD

**Issue by ChouUn** [rwv/chinese-dos-games#24]
**游戏简体中文名：** 太阁立志传
**游戏繁体中文名：** 太閤立志傳
**游戏英文名：** Taikō Risshiden
**游戏发行年份：** 1992
**游戏下载地址（可选）：** http://7xjw62.com1.z0.glb.clouddn.com/taikou1.zip
**游戏封面图地址（可选）：**
**其他（如键位、秘籍、链接等等）（可选）：**

游戏是我重新打包的，来源为 http://www.pc6.com/softview/SoftView_99916.html。
executable 设置为 PLAY.BAT，亲测可用。

**Comment by ChouUn** [comment]
#18

**Comment by ChouUn** [comment]
@rwv 其实这个游戏还有个问题，要按一下回车才能正常开始，不像别的能自动开始。
闲的时候能帮忙研究下吗？

**Comment by rwv** [comment]
@ChouUn OK 但短时间内估计没有时间研究

**Comment by ChouUn** [comment]
@rwv 无妨，毕竟单个游戏的优先级不是很高，只是比较好奇这个的原因。
我看你加了按 Enter 开始游戏的提示，已经很细心了。
