### ISSUE TITLE
下载游戏报错

### ISSUE THREAD

**Issue by FireLustre** [rwv/chinese-dos-games#26]
**bug 描述**
python3.6运行 `python3 download_data.py`
报错信息
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

**如何重现**
macOS系统下运行
`python3 download_data.py`

**预期情况**
正常下载游戏

**截图**

![image](https://user-images.githubusercontent.com/16452711/45135899-472b4000-b1d4-11e8-865c-c66c21483b09.png)

**系统环境**
操作系统：macOS
浏览器：chrome
游戏：下载游戏的时候

**Comment by rwv** [comment]
无法重现，看起来似乎和证书有关。会不会是系统证书出问题了？

**Comment by FireLustre** [comment]
嗯，官方的ReadMe.rtf中说明了Python3.6不再使用由系统提供的证书，且本身也并不包含证书，需要安装 certifi 的证书包。
在命令行跑了`/Applications/Python\ 3.6/Install\ Certificates.command`之后就可以了。

**Comment by 2niuhe** [comment]
```shell
pip install certifi
pip install incremental
```
solve this problem in my computer.
env:
- python3.6
- Linux

**Comment by neighbour1208b** [comment]
大富翁2不能使用。

**Comment by AUENDXYZ** [comment]
可以下载，很有意思的收藏。谢谢！

**Comment by Airy-L** [comment]
下载失败，无错误提示，下载后的压缩包全部是 4k大小，是什么原因？硬盘ntfs的原因？

**Comment by rwv** [comment]
请检查下载域名
2022年4月23日 +0800 13:35 Airy-L ***@***.***>，写道：

**Comment by Airy-L** [comment]
> 请检查下载域名 2022年4月23日 +0800 13:35 Airy-L ***@***.***>，写道：
> […](#)
> 下载失败，无错误提示，下载后的压缩包全部是 4k大小，是什么原因？硬盘ntfs的原因？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

谢谢，替换了一下脚本。现在正常下载中

**Comment by zhengmz** [comment]
现在下载不了

#230

**Comment by infbighead** [comment]
[女皇杯(日)] 無法運行

**Comment by CatMoonzero** [comment]
arm64的机器无法部署，是不支持吗？

**Comment by sqxinquan** [comment]
无法下载游戏

**Comment by shiyebushihua** [comment]
> > 请检查下载域名 2022年4月23日 +0800 13:35 Airy-L _**@**_._**>，写道：
> > […](#)
> > 下载失败，无错误提示，下载后的压缩包全部是 4k大小，是什么原因？硬盘ntfs的原因？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.**_>
> 
> 谢谢，替换了一下脚本。现在正常下载中

我的也是4k 这个是什么问题呀老哥

**Comment by CatMoonzero** [comment]
我也不知道，现在还没解决呢

wangjianhuaa ***@***.***> 于 2025年1月16日周四 17:59写道：

**Comment by zhaoyan0528** [comment]
File "download_data.py", line 34
    print(f'Downloading {identifier} game file')
你好，在1panel下运行download_data.py提示这个错误，我怎么解决？
第34行是这个
def download(identifier, url, file):
    print(f'Downloading {identifier} game file')
    urllib.request.urlretrieve(url, file)
