### ISSUE TITLE
非洲探险2

### ISSUE THREAD

**Issue by ctyytc** [rwv/chinese-dos-games#27]
**游戏简体中文名：非洲探险2** 
**游戏繁体中文名：非洲探險2**
**游戏英文名：Crazy Adventure in Africa2**
**游戏发行年份：**
**游戏下载地址（可选）：http://www.nicesoftware.co/2015/05/crazy-adventure-in-africa2.html**
**游戏封面图地址（可选）：https://1.bp.blogspot.com/-OX0PkLvxg5g/VWhtcVfyvqI/AAAAAAAALjM/AAevYmwoUOo/s400/1.jpg**
**其他（如键位、秘籍、链接等等）（可选）：**

**Comment by rwv** [comment]
https://dos.zczc.cz/games/非洲探险2/
