### ISSUE TITLE
皇帝怎么网页无法使用键盘?

### ISSUE THREAD

**Issue by MarsZone** [rwv/chinese-dos-games#28]
**要求的功能**
描述功能

**优先度**
* [ ] 高
* [ ] 中
* [ ] 低
是要下载下来才能操作么?
Mac可不可以用?

**Comment by rwv** [comment]
皇帝由于没有玩过不大清楚，但是我用鼠标操作好像没有障碍？开场画面可以用右键跳过。操作是需要等资源包下载下来才能操作。Mac 可以使用，在 Chrome, Safari, Firefox Mac 版本上都测试通过。

**Comment by MarsZone** [comment]
好吧.了解了.这个要使用右键才可以跳过开场动画..=.= 惊了,这个DOS模拟器竟然还支持右键.
我下载到本地了.

**Comment by MarsZone** [comment]
唔....但是用手机就没办法右键了呀...能有什么方法右键跳过么.

**Comment by rwv** [comment]
目前没有支持手机的计划，因为手机即时支持了右键也没法移动光标。

**Comment by MarsZone** [comment]
哦哦。。。不过作者你为何这么优秀？？？你就算能模拟DOS也还好。。这些游戏就很难得了。。简直算是古董级的了。
