### ISSUE TITLE
太阁立志传无法进入游戏

### ISSUE THREAD

**Issue by netdigger** [rwv/chinese-dos-games#29]
**bug 描述**
进入属性设置后，按键和退出模拟器的按键冲突，导至无法继续

**截图**
![image](https://user-images.githubusercontent.com/1217340/45153382-de6db300-b227-11e8-9d0e-f97d39b18ccb.png)

**如何重现**
新建角色

**预期情况**
按ESC进入下一步

**系统环境**
操作系统：MacOS
浏览器：Chrome
游戏：太阁立志传

**Comment by rwv** [comment]
这是一个已知bug，需要连按两次 esc 键

**Comment by shaoconghou** [comment]
连着按好几次也进入不了游戏…

**Comment by rwv** [comment]
@shaoconghou 本人测试成功，请问您的系统环境是什么？

**Comment by shaoconghou** [comment]
> @shaoconghou 本人测试成功，请问您的系统环境是什么？

在windows 10 和 macos 10.13的chrome 68上都不行，按一次esc键会让鼠标退出模拟器，再多次按esc键也无法退出属性设置窗口

**Comment by rwv** [comment]
我又尝试了一次，还是无法重现这个问题
macOS 10.13.5 && Chrome 68.0.3440.106 (Official Build) (64-bit)
![screen shot 2018-09-18 at 12 48 37 pm](https://user-images.githubusercontent.com/7891383/45664943-2ef6e180-bb41-11e8-988a-5c9f290312b2.png)

**Comment by shaoconghou** [comment]
> @shaoconghou 我又尝试了一次，还是无法重现这个问题
> macOS 10.13.5 && Chrome 68.0.3440.106 (Official Build) (64-bit)
> ![screen shot 2018-09-18 at 12 48 37 pm](https://user-images.githubusercontent.com/7891383/45664943-2ef6e180-bb41-11e8-988a-5c9f290312b2.png)

我明白是为什么了，是游戏没玩对，必须把优待值分配完（为0）之后才能进行下一步，我以为可以留着一些等进入游戏之后再看情况分配，所以无法进入游戏。
现在没有问题了，抱歉打扰了！
