### ISSUE TITLE
主题医院没有声音

### ISSUE THREAD

**Issue by wupi** [rwv/chinese-dos-games#3]
**bug 描述**
主题医院没有任何声音
其他游戏没有这个问题。

**如何重现**
正常游戏即可重现。

**预期情况**
有音效，有音乐。

**截图**
N/A

**系统环境**
操作系统： win10
浏览器：firefox
游戏：主题医院

**Comment by rwv** [comment]
已重现，但声音目前优先级较低，需要先解决其他 issue.

**Comment by rwv** [comment]
有声音的版本文件大小有 150 MB，实在是有点大，很有可能会破坏用户体验

**Comment by radius-yf** [comment]
主要就是想听那句 请患者不要死在走廊上

**Comment by rwv** [comment]
或者专门放一个有声音的版本和没声音的版本

**Comment by rwv** [comment]
@wupi @radius-yf https://dos.zczc.cz/games/主题医院S/
此为有声音版
