### ISSUE TITLE
无法运行 app.py

### ISSUE THREAD

**Issue by kong6wu6wu** [rwv/chinese-dos-games#30]
**bug 描述**
bug 的描述
运行指令 python3 app.py      报错：
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：mac os
浏览器：
游戏：

**Comment by DrayChou** [comment]
pip install flask
kong6wu6wu <notifications@github.com>於 2018年9月6日 週四，20:43寫道：

**Comment by rwv** [comment]
已有人发出解决方案，关闭issue
