### ISSUE TITLE
请加上《艾蒂丝魔法大冒险》

### ISSUE THREAD

**Issue by latte405** [rwv/chinese-dos-games#31]
**游戏简体中文名：《艾蒂丝魔法大冒险》
**游戏繁体中文名：《艾蒂絲魔法大冒險》
**游戏英文名：《Adith the forgotten alchemy》
**游戏发行年份：1999年
**游戏下载地址（可选）：http://www.acgwolf.com/viewthread.php?tid=32880 需要50积分才能看到😰
                                           积分不够看不到附件😭

**Comment by rwv** [comment]
找不到可用的游戏文件，请问可以帮忙在网上找到可用的游戏文件吗

**Comment by latte405** [comment]
o(╥﹏╥)o
只找到了2个失效的电驴链接，下载毫无速度。。。

**Comment by rwv** [comment]
@playerlin 已下載。

**Comment by rwv** [comment]
fixed 但运行速度不够理想

**Comment by rwv** [comment]
https://dos.zczc.cz/games/艾蒂丝魔法大冒险/
