### ISSUE TITLE
请添加《抗日：地雷战》

### ISSUE THREAD

**Issue by xiaojie9509** [rwv/chinese-dos-games#32]
**游戏简体中文名：** 抗日：地雷战
**游戏繁体中文名：**
**游戏英文名：**
**游戏发行年份：** 1998
**游戏下载地址（可选）：** 链接：http://pan.baidu.com/s/1nvqBAJZ 密码：msui
**游戏封面图地址（可选）：**
**其他（如键位、秘籍、链接等等）（可选）：**
百度百科介绍：https://baike.baidu.com/item/%E6%8A%97%E6%97%A5%E5%9C%B0%E9%9B%B7%E6%88%98
攻略：
http://blog.sina.com.cn/s/blog_4c92851e0100elgq.html
http://blog.sina.com.cn/s/blog_4c92851e0100elgs.html

**Comment by rwv** [comment]
百度百科看起来平台是Windows 95，先行关闭issue，有什么问题请您重新打开issue
