### ISSUE TITLE
请添加《决战朝鲜》

### ISSUE THREAD

**Issue by xiaojie9509** [rwv/chinese-dos-games#33]
**游戏简体中文名：** 决战朝鲜
**游戏繁体中文名：**
**游戏英文名：**
**游戏发行年份：** 1999
**游戏下载地址（可选）：**http://www.pc6.com/softview/SoftView_72803.html
**游戏封面图地址（可选）：**
**其他（如键位、秘籍、链接等等）（可选）：**
百度百科介绍：https://baike.baidu.com/item/%E5%86%B3%E6%88%98%E6%9C%9D%E9%B2%9C/2896
攻略：
http://blog.sina.com.cn/s/blog_4ee5f39d010126re.html

**Comment by rwv** [comment]
提供的下载地址非 DOS 版本，同时搜索不到 DOS 版本的决战朝鲜，先行关闭 issue，如果有问题请重开此 issue.
