### ISSUE TITLE
可不可以下载上传游戏存档

### ISSUE THREAD

**Issue by netdigger** [rwv/chinese-dos-games#34]
**要求的功能**
鉴于实现内存修改器可能比较麻烦，那么下载游戏存档是否容易可行一些？这样可以下载游戏存档修改后再上传也可以实现游戏修改。

**优先度**
* [ ] 高
* [x] 中
* [ ] 低

**Comment by iPandaJC** [comment]
需要金山游侠出马

**Comment by rwv** [comment]
added
