### ISSUE TITLE
金庸群侠传 中文输入

### ISSUE THREAD

**Issue by wuming2** [rwv/chinese-dos-games#36]
**bug 描述**
游戏启动，要输入中文，无法输入，回车键无效

**如何重现**

**预期情况**
先手动点个赞👍

**截图**

**系统环境**
操作系统：macOs sierra   
浏览器：chrome
游戏：金庸群侠传
使用vimium 不知是否有影响

**Comment by rwv** [comment]
输入中文是注音输入法，我对注音不大了解。假如对名字没有要求的话随便打几个字母按空格数字键选字。然后回车进入。
