### ISSUE TITLE
执行download_data.py时，会重新下载已经下载好的游戏

### ISSUE THREAD

**Issue by WangDePeng7** [rwv/chinese-dos-games#37]
**要求的功能**
描述功能

**优先度**
* [ ] 高
* [ ] 中
* [ ] 低

**Comment by WangDePeng7** [comment]
第一次执行download_data.py时，已经下载了三个游戏，但是出于网络异常，进程崩溃了，重新执行，还是会从第一个游戏开始下载~

**Comment by argan** [comment]
我用下面的脚本来下载
`

#!/bin/bash
names=`grep identifier games.json |awk -F'"' '{print $4}'`

PREFIX="https://dos.zczc.cz/static/gamedata/"
DEST='./static/gamedata/'

for identifier in $names;do
    file="$DEST$identifier.zip"
    if [ -f $file ];then
        echo "$file exists."
    else
        echo wget -c "$PREFIX$identifier.zip" -O $file
        wget -c "$PREFIX$identifier.zip" -O "$DEST$identifier.zip"
    fi
done
`

**Comment by argan** [comment]
怎么贴的代码没缩进了

**Comment by rwv** [comment]
@argan 已帮忙修改缩进

**Comment by rwv** [comment]
fixed
