### ISSUE TITLE
不考虑加个dos版的红警吗，有低分辨率的ra95的

### ISSUE THREAD

**Issue by kero990** [rwv/chinese-dos-games#38]
**游戏简体中文名：红色警戒95
**游戏繁体中文名：
**游戏英文名：Command Conquer:Red Alert95
**游戏发行年份：1996
**游戏下载地址（可选）：**
**游戏封面图地址（可选）：**
**其他（如键位、秘籍、链接等等）（可选）：ra95是双模式版一般的安装包都有win模式程序（即ra.exe），和dos模式程序（rungame.exe）
贴吧有dos版安装和运行教程

**Comment by kero990** [comment]
我不知道他这个汉化版行不行，他可能是基于某个win10可以运行的重制修正版，所以也许dos下不行。你还是找找dosbox的整合包之类

发送自 Windows 10 版邮件应用

发件人: seedgou
发送时间: 2018年9月9日 1:21
收件人: rwv/chinese-dos-games
抄送: kero990; Author
主题: Re: [rwv/chinese-dos-games] 不考虑加个dos版的红警吗，有低分辨率的ra95的 (#38)

你好，是这个吗？
https://tieba.baidu.com/p/5712785022

**Comment by GoogleLLP** [comment]
请问您有可用的资源吗？地址在哪里？
