### ISSUE TITLE
readme.md 中應該提示要先安裝flask

### ISSUE THREAD

**Issue by Shihyen** [rwv/chinese-dos-games#39]
**bug 描述**
照著readme.md操作，會卡在沒有套件flask，對於不熟悉python的朋友來說有點障礙。

**如何重现**
python3 app.py

**预期情况**
先安裝 flask
pip3 install flask

**系统环境**
操作系统：mac 
浏览器：
游戏：

**Comment by rwv** [comment]
fixed
