### ISSUE TITLE
Android版Chrome不支持OTG鼠标在游戏内的使用

### ISSUE THREAD

**Issue by pzkpfwiii** [rwv/chinese-dos-games#40]
**bug 描述**
Android版Chrome不支持OTG鼠标在游戏内的使用，点击无效

**如何重现**
用OTG线连接鼠标和手机，鼠标可用，在chrome中打开dos.zczc.cz，进入游戏，鼠标点击游戏屏幕无效。

**预期情况**
鼠标点击后进入游戏鼠标模式

**截图**
暂无

**系统环境**
操作系统：Flyme 5.2.7.2A(Android 6.0.1)
浏览器：Chrome 59.0.3071.125
游戏：银河英雄传说3SP

**Comment by rwv** [comment]
由于身边没有 Android 设备和 OTG 线，无法 debug，抱歉了。

**Comment by rwv** [comment]
似乎 Puffin Browser 可以有模拟键鼠的功能

**Comment by a18project** [comment]
Android 建议用独立的 DOSBox APP，很多带有虚拟键盘/手柄的支持
