### ISSUE TITLE
请添加《卧龙传》

### ISSUE THREAD

**Issue by RuralHunter** [rwv/chinese-dos-games#42]
**游戏简体中文名：卧龙传
**游戏繁体中文名：**
**游戏英文名：**
**游戏发行年份：**
**游戏下载地址（可选）：**
**游戏封面图地址（可选）：**
**其他（如键位、秘籍、链接等等）（可选）：**

**Comment by playerlin** [comment]
https://1drv.ms/u/s!AmgqNiQT9V2Phn2Aq0Hl9UkGR4ud

從某合輯中取得，連結點下後，被選定的WDRAGON.RAR(1.60MB, RAR4壓縮)，可能會自動進行下載。同樣，若可下載執行並添加後請告知，將會把文件從連結中的目錄移除。

**Comment by rwv** [comment]
@playerlin 已下載

**Comment by RuralHunter** [comment]
多谢！
