### ISSUE TITLE
请求增加游戏“麻将情趣屋2”

### ISSUE THREAD

**Issue by heigell** [rwv/chinese-dos-games#46]
游戏简体中文名：麻将情趣屋2
游戏繁体中文名：麻将情趣屋II
游戏发行年份：1995年
游戏下载地址（可选）：http://small.bxamp.com/dos/MJ2.rar 不知道能不能下载了，自带dos模拟器
游戏封面图地址（可选）：http://lh4.ggpht.com/-yxpVAwc9I8g/TfoUxGKZjrI/AAAAAAAAgCE/-hYshYscr58/s640/110527_352_mjqqw2000.jpg
其他（如键位、秘籍、链接等等）（可选）：http://chiuinan.github.io/game/game/intro/ch/c42/mj2.htm

**Comment by rwv** [comment]
https://dos.zczc.cz/games/%E9%BA%BB%E5%B0%86%E6%83%85%E8%B6%A3%E5%B1%8B2/
