### ISSUE TITLE
轩辕剑1不完整

### ISSUE THREAD

**Issue by houndpan** [rwv/chinese-dos-games#48]
**bug 描述**
轩辕剑1在开始后没多久需要下水井之后会弹出窗口提示插入磁盘2，游戏无法继续进行

**如何重现**
拿到绳子下水井后向左行走一小段距离

**预期情况**
正常游戏，不需要插入磁盘2

**系统环境**
操作系统：win10
浏览器：chrome
游戏：轩辕剑1

**Comment by rwv** [comment]
看来是游戏文件的问题，需要正确的游戏文件。

**Comment by xyb** [comment]
这里下载的游戏文件看起来是完整的：http://www.pc6.com/softview/SoftView_102143.html

**Comment by xyb** [comment]
@rwv 我已经测试过，前面给出的链接下载的是完整版本。

**Comment by rwv** [comment]
@xyb 谢谢！
