### ISSUE TITLE
iOS Safari 主题医院无法运行

### ISSUE THREAD

**Issue by alanzchen** [rwv/chinese-dos-games#49]
**bug 描述**
如图

**如何重现**
使用 iOS 浏览器打开主题医院

**预期情况**
游戏正常运行

**截图**
![43e9543c-1921-4edf-a202-9b5e31dd930e](https://user-images.githubusercontent.com/2144783/45272921-980d9380-b475-11e8-97a4-4af39d6e3a5d.png)

**系统环境**
操作系统：iOS 11.4
浏览器：Safari
游戏：主题医院

**Comment by rwv** [comment]
很抱歉，目前移动端还不受支持。
