### ISSUE TITLE
保存进度

### ISSUE THREAD

**Issue by scavin** [rwv/chinese-dos-games#5]
**要求的功能**
刚刚玩了下金庸群侠传，保存进度后退出游戏。关闭标签页后重新打开，并没有保存下之前的进度。

**优先度**
* [x] 高
* [ ] 中
* [ ] 低

**Comment by rwv** [comment]
存档的确现在还没有做完，因为 Emscripten 不能十分方便的保存存档，现在主要可能的解决方案有两个。一个是 https://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html#filesystem-api-idbfs 另一个是 http://github.com/copy/v86。使用 v86 我已经做出可以存档的 DEMO 了，但 v86 仍然有些 bug 使得 DEMO 基本上不可用。

**Comment by watermoonchandra** [comment]
不能保存进度是个大问题，这些大型游戏不可能一口气就通关。

**Comment by rwv** [comment]
@scavin @argan @watermoonchandra 存档功能完成！

**Comment by watermoonchandra** [comment]
太棒了！测试过刷新网页，关掉窗口，关掉浏览器，甚至重启系统都可以玩到存档，实在是解决大问题了！

**Comment by Fredpata** [comment]
我的存档丢失了……不知道为什么

**Comment by laurencecao** [comment]
> [@rwv](https://github.com/rwv) 用 https://bellard.org/jslinux/ 试试看？

所以它是怎么save data的呢？我在绿联的NAS上用docker跑web，但是docker里面看不到任何的个性化数据，难道真是存在cookie中的？
