### ISSUE TITLE
VRBB 青少棒扬威记

### ISSUE THREAD

**Issue by justintien** [rwv/chinese-dos-games#53]
**游戏简体中文名：** VRBB 青少棒扬威记
**游戏繁体中文名：** VRBB 青少棒扬威记
**游戏英文名：** VRBB
**游戏发行年份：**
**游戏下载地址（可选）：**
https://mega.nz/#!qgcHXZ7Y!_eydkvFwdP7hIvUKKEROwH8cV4tLamqxmcbSvAo271s

**游戏封面图地址（可选）：**
介绍 https://weisonchang.tian.yam.com/posts/35874170
**其他（如键位、秘籍、链接等等）（可选）：**
密技 http://kent99.tripod.com/secrect.htm#VR%E9%9D%92%E5%B0%91%E6%A3%92%E6%8F%9A%E5%A8%81%E8%A8%98%E5%AF%86%E6%8A%80

**Comment by rwv** [comment]
https://dos.zczc.cz/games/青少棒扬威记/
