### ISSUE TITLE
侠客英雄传3

### ISSUE THREAD

**Issue by abcfy2** [rwv/chinese-dos-games#55]
**游戏简体中文名：** 侠客英雄传3
**游戏繁体中文名：**
**游戏英文名：**
**游戏发行年份：**
**游戏下载地址（可选）：** http://www.mhhf.com/gamev-3765
**游戏封面图地址（可选）：** 
**其他（如键位、秘籍、链接等等）（可选）：**

**Comment by rwv** [comment]
完成！https://dos.zczc.cz/games/侠客英雄传3/

**Comment by abcfy2** [comment]
![image](https://user-images.githubusercontent.com/5327677/45751115-f25fde80-bc43-11e8-810f-ae2a0969740d.png)
运行就直接报错了

**Comment by rwv** [comment]
已记录。
