### ISSUE TITLE
不可思议的机器

### ISSUE THREAD

**Issue by abcfy2** [rwv/chinese-dos-games#56]
**游戏简体中文名：** 不可思议的机器
**游戏繁体中文名：**
**游戏英文名：** The Incredible Machine
**游戏发行年份：**
**游戏下载地址（可选）：** https://www.dosgamesarchive.com/download/the-incredible-machine/
**游戏封面图地址（可选）：** ![](https://image.dosgamesarchive.com/screenshots/small/incrediblemachine1.gif)
**其他（如键位、秘籍、链接等等）（可选）：**

**Comment by abcfy2** [comment]
尽管这个游戏不是中文的，但儿时在完全不懂英文的情况下也玩的津津有味，完全靠猜通关条件来玩的

**Comment by rwv** [comment]
十分抱歉，非中文游戏目前暂不考虑。
