### ISSUE TITLE
三国演义

### ISSUE THREAD

**Issue by ShunyangLi0812** [rwv/chinese-dos-games#57]
**bug 描述**
bug 的描述
三国演义不能打开游戏页面，只会停留在dos页面

**如何重现**
如何重现这个 bug
打开游戏

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：
浏览器：
游戏：

**Comment by rwv** [comment]
请问您的操作系统，浏览器？

**Comment by rwv** [comment]
需要按几次2选择驱动，macOS 10.13.5 && Version 11.1.1 (13605.2.8) 测试运行成功。
