### ISSUE TITLE
能否增加存档修改或者内存修改的功能？

### ISSUE THREAD

**Issue by wasamii926** [rwv/chinese-dos-games#59]
**要求的功能**
不清楚这种网页模式的游戏存档是保存在哪里？
能否增加游戏存档文件的16进制读取修改保存功能，或者增加内存修改功能，就是搜索目标—记录搜索记录—回到游戏变更目标值—根据搜索记录再次搜索目标—找到内存地址—修改保存。

**优先度**
* [ ] 高
* [x] 中
* [ ] 低

**Comment by rwv** [comment]
duplicate with #14  #34

**Comment by rwv** [comment]
游戏存档保存在 Indexdb 中，修改功能需要内嵌 FPE

**Comment by rwv** [comment]
@wasamii926 应该是的，但估计不好修改。
