### ISSUE TITLE
《模拟城市2000》无法正常启动

### ISSUE THREAD

**Issue by wujians** [rwv/chinese-dos-games#6]
《模拟城市2000》无法正常启动，提示配置文件损坏。

**Comment by rwv** [comment]
已重现

**Comment by rwv** [comment]
Fixed. 请清除缓存刷新后查看，

**Comment by Damocs0921** [comment]
似乎依然存在，这个游戏是不是不兼容mac系统下的浏览器？

**Comment by rwv** [comment]
@Damocs0921 在 mac Safari 和 Chrome 均运行成功，试试清理缓存？
