### ISSUE TITLE
DOS游戏合集

### ISSUE THREAD

**Issue by qwe820905** [rwv/chinese-dos-games#62]
**游戏简体中文名：*DOS游戏合集（游戏列表在分享里有）* 
**游戏繁体中文名：**
**游戏英文名：**
**游戏发行年份：**
**游戏下载地址（可选）：*链接: https://pan.baidu.com/s/1eqQq0UmczDKL5aVOVk2T2Q 密码: smvk*
**游戏封面图地址（可选）：**
**其他（如键位、秘籍、链接等等）（可选）：**

**Comment by rwv** [comment]
您好，这个之前已经有其他网友发送给我了，已经打包好了，但是由于上传速度较慢，目前仍在上传到 vps 上。

**Comment by creepycas** [comment]
> 您好，这个之前已经有其他网友发送给我了，已经打包好了，但是由于上传速度较慢，目前仍在上传到 vps 上。

非常感谢～～～

**Comment by rwv** [comment]
Done
