### ISSUE TITLE
如何自行增加游戏？有没有文档？

### ISSUE THREAD

**Issue by shawnchain** [rwv/chinese-dos-games#64]
**要求的功能**
如题，如何自行增加游戏？对ZIP包是否有特殊目录要求？是否存在配置文件？

**优先度**
* [x] 高
* [ ] 中
* [ ] 低

**Comment by rwv** [comment]
您好，可以看一下项目目录下的 `CONTRIBUTING.md`
zip 包的要求的话主要是尽量不要有目录结构，具体命令应该是这样的 `zip -r test.zip .` (在游戏文件目录下)
配置文件可以在游戏文件目录下附上 `dosbox.conf` 文件
