### ISSUE TITLE
在根目录下运行 Python 3 脚本 download_data.py 报错

### ISSUE THREAD

**Issue by charles0769** [rwv/chinese-dos-games#65]
**bug 描述**
bug 的描述 在根目录下运行 Python 3 脚本 download_data.py 报错

**如何重现**
如何重现这个 bug 根目录下运行python3 download_data.py

**预期情况**
你预期的正常情况下载游戏成功

**截图**
bug 的截图
[http://cdn.dianchouapp.com/Fhp3mf9mJfif7fzMOythUdZ36CIC](url)

**系统环境**
操作系统：centOS 7.3
浏览器：
游戏：

**Comment by rwv** [comment]
先行关闭，如果有其他问题可以重开这个 issue

**Comment by charles0769** [comment]
感谢，重新安装python环境后可以下载，已解决！
