### ISSUE TITLE
富甲天下二不能玩

### ISSUE THREAD

**Issue by netdigger** [rwv/chinese-dos-games#66]
**bug 描述**
不能进入游戏，提示没有cdrom

**如何重现**
任意进入

**预期情况**
能够玩

**截图**

![image](https://user-images.githubusercontent.com/1217340/45797219-a9b62d00-bcf8-11e8-92d2-15e430fd405b.png)

**系统环境**
操作系统：Mac os
浏览器：chrome
游戏：富甲天下

**Comment by rwv** [comment]
fixed. https://dos.zczc.cz/games/富甲天下2/
