### ISSUE TITLE
炎龙骑士团外传载入失败

### ISSUE THREAD

**Issue by koww** [rwv/chinese-dos-games#67]
**bug 描述**
炎龙骑士团外传载入失败

**如何重现**
打开炎龙骑士团外传，会提示载入CD ROM失败

**预期情况**
直接进入游戏

**截图**
无截图

**系统环境**
操作系统：Win10
浏览器：Chrome
游戏：FDPS

**Comment by rwv** [comment]
fixed https://dos.zczc.cz/games/%E7%82%8E%E9%BE%99%E9%AA%91%E5%A3%AB%E5%9B%A2/

**Comment by koww** [comment]
No it's not. 
**外传**依然失败。

**Comment by rwv** [comment]
https://dos.zczc.cz/games/炎龙骑士团外传/
