### ISSUE TITLE
吞食天地4 加载失败

### ISSUE THREAD

**Issue by sumhat** [rwv/chinese-dos-games#68]
**bug 描述**
游戏加载时显示 "No DATA CDROM"，然后就无法继续了

**如何重现**
加载此游戏：https://dos.zczc.cz/games/%E5%90%9E%E9%A3%9F%E5%A4%A9%E5%9C%B04/

**预期情况**
游戏正常运行

**截图**
<img width="749" alt="screen shot 2018-09-26 at 10 18 33 pm" src="https://user-images.githubusercontent.com/4574168/46106947-6537ff00-c1da-11e8-845f-73a97ef398e7.png">

**系统环境**
操作系统：MacOS  High Sierra
浏览器：Chrome 69.0.3497.100
游戏：吞食天地4

**Comment by rwv** [comment]
应该已经修复了，游戏资源过大未能测试运行成功，如有问题请重开此 issue
