### ISSUE TITLE
Chrome游戏都打不开了 除非清除缓存，或者进入incognito

### ISSUE THREAD

**Issue by mikupa55** [rwv/chinese-dos-games#69]
**bug 描述**
bug 的描述

**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：
浏览器：
游戏：

**Comment by mikupa55** [comment]
![image](https://user-images.githubusercontent.com/12191163/46241453-cdf6c580-c3ec-11e8-89b2-6b487903265d.png)

**Comment by rwv** [comment]
谢谢反馈，请问能否有方法重现这个bug吗，另请您附上开发者工具的截图

**Comment by mikupa55** [comment]
![image](https://user-images.githubusercontent.com/12191163/46242041-ef0fe400-c3f5-11e8-9ed7-7a2ed697ee88.png)

**Comment by mikupa55** [comment]
不清楚，玩着玩着就这样了。除非清除缓存重置模拟器

**Comment by pengan1987** [comment]
我发现问题的原因了，因为每个不同的游戏都使用同一个名为"emularity"的IndexedDB，所以导致其他游戏会留下配置文件在文件系统里。
解决的办法是针对不同的游戏在创建模拟器的时候加入
```javascript
DosBoxLoader.fileSystemKey(gamekey)
```
利用gamekey来区分不同的游戏，这样每个游戏就有自己独立的文件系统，不会互相干扰了
