### ISSUE TITLE
殖民计划无法显示全部界面

### ISSUE THREAD

**Issue by heigell** [rwv/chinese-dos-games#7]
殖民计划无法显示全部界面，而且由于游戏中的“esc”键与浏览器系统的“esc”键冲突，导致游戏中无法进行简单的退出当前显示界面的操作。

**Comment by rwv** [comment]
无法显示全部界面无法重现，有截图吗？另浏览器是什么

**Comment by rwv** [comment]
esc 键冲突会出现在键盘和鼠标共用的游戏上，现在还没有很好的解决方法

**Comment by rwv** [comment]
无回应，先行关闭。
