### ISSUE TITLE
网页全屏后怎样退回来？

### ISSUE THREAD

**Issue by tomatopoteto** [rwv/chinese-dos-games#70]
**要求的功能**
描述功能
就标题的内容，别的没什么了，谢谢

**优先度**
* [ ] 高
* [ ] 中
* [ ] 低

**Comment by journey-ad** [comment]
按 <kbd>Esc</kbd> 或 <kbd>F11</kbd>

**Comment by rwv** [comment]
“网页全屏”右下角有个退出按钮
