### ISSUE TITLE
无声狂啸运行失败

### ISSUE THREAD

**Issue by blurrymargin** [rwv/chinese-dos-games#75]
**bug 描述**
无法正常运行，出现"Can't open music resource file"后就跳出，命令提示符也随后转至"C:\DRIVERS\"

**如何重现**
https://dos.zczc.cz/games/%E6%97%A0%E5%A3%B0%E7%8B%82%E5%95%B8/

**预期情况**
游戏正常运行

**截图**
![default](https://user-images.githubusercontent.com/42903697/46232668-7af82080-c3a2-11e8-914b-9c27ab083472.PNG)

**系统环境**
操作系统：win10 2018/9/29
浏览器：Waterfox 56.2.3 (64-bit)
游戏：无声狂啸

**Comment by bingzheyuan** [comment]
:rofl: 打不开音乐文件，所以叫无声狂笑

**Comment by rwv** [comment]
目前没找出解决办法。

**Comment by rwv** [comment]
fixed
