### ISSUE TITLE
很多游戏都玩不了，说没有光驱驱动

### ISSUE THREAD

**Issue by xiaoyaohust** [rwv/chinese-dos-games#76]
用的WINDOWS10或者MAC的chrome, 例子有超时空英雄传说2，超时空英雄传说2SP，三国演义2

**Comment by rwv** [comment]
https://gist.github.com/rwv/a35181ba8b22147eb14be4fbedfbe6f2 
https://tieba.baidu.com/p/3962261741 中的说明文件，需要处理一下。

**Comment by rwv** [comment]
应该已经修复了，但游戏文件太大没能测试运行，如有其他问题请重开此 issue

**Comment by rwv** [comment]
超时空英雄传说2为iso格式为非cdrom 修复失败

**Comment by rwv** [comment]
需要修改 emularity 
参见 https://www.dosbox.com/wiki/MOUNT#Mounting_an_ISO-File_as_volume

**Comment by rwv** [comment]
应该已经修复完成 #79
