### ISSUE TITLE
存档导出功能

### ISSUE THREAD

**Issue by rwv** [rwv/chinese-dos-games#78]
导出对应的 Indexeddb 文件。

**Comment by rwv** [comment]
Arraybuffer 需要先转换成 uint8array 再转换成 Base64

**Comment by ferocknew** [comment]
存档是存浏览器里的？

**Comment by rwv** [comment]
@ferocknew 现在是存在浏览器里 Indexeddb 中

**Comment by hlx98007** [comment]
能从developer tools看到indexeddb，如何把数据导出到文件？

**Comment by gavin77424** [comment]
可以在遊戲網頁下邊有一個導出存檔。之後如果要到另外一台讀檔，請先把indexeddb底下的遊戲紀錄刪掉在用網頁的導入存檔

**Comment by rwv** [comment]
added
