### ISSUE TITLE
网站无法打开

### ISSUE THREAD

**Issue by barnett2010** [rwv/chinese-dos-games#8]
**bug 描述**
网站无法打开。dos.zczc.cz
提示超时

ping dos.zczc.cz

正在 Ping dos.zczc.cz [104.27.182.126] 具有 32 字节的数据:
来自 104.27.182.126 的回复: 字节=32 时间=159ms TTL=53
来自 104.27.182.126 的回复: 字节=32 时间=159ms TTL=53
来自 104.27.182.126 的回复: 字节=32 时间=159ms TTL=53
来自 104.27.182.126 的回复: 字节=32 时间=158ms TTL=53

104.27.182.126 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 158ms，最长 = 159ms，平均 = 158ms

**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：
浏览器：
游戏：

**Comment by rwv** [comment]
无法重现，ping的结果不是正常吗？

**Comment by rwv** [comment]
无回应，先行关闭。
