### ISSUE TITLE
银河英雄传说4EX  启动失败

### ISSUE THREAD

**Issue by NeoKarajan** [rwv/chinese-dos-games#82]
启动后自动执行autoexec
然后执行mount c /emulator/c -t iso 提示illegal type iso

然后就是driver C dose not exist!

**Comment by rwv** [comment]
#79 
https://github.com/rwv/chinese-dos-games/blob/master/games.json#L15520

**Comment by rwv** [comment]
暂时解决方案：
运行 `imgmount d /emulator/c/G4X.iso -t iso -fs iso`
然后运行 `G4X`

**Comment by rwv** [comment]
应该已经修复完成 #79
