### ISSUE TITLE
《剑芒罗曼史》卡在初始画面进不去

### ISSUE THREAD

**Issue by ajielee** [rwv/chinese-dos-games#84]
**bug 描述**
《剑芒罗曼史》卡在初始画面进不去: [link](https://dos.zczc.cz/games/%E5%89%91%E8%8A%92%E7%BD%97%E6%9B%BC%E5%8F%B2/)

**如何重现**
打开页面即可

**预期情况**
能正常游戏

**截图**
<img width="755" alt="2018-10-18 8 41 14" src="https://user-images.githubusercontent.com/1598600/47191580-54306880-d316-11e8-9f25-97c5755c05fa.png">

**系统环境**
操作系统：macOS 10.14
浏览器：Chrome
游戏：剑芒罗曼史

**Comment by larryli** [comment]
按 ESC 键就可以了啊。
![default](https://user-images.githubusercontent.com/10723/47896402-5a8f1a80-dea8-11e8-8dea-18e76213c171.png)

**Comment by ajielee** [comment]
是修复过吗？现在画面跟上次不一样，正常了，谢谢。
