### ISSUE TITLE
红楼梦 十二金钗不能加载

### ISSUE THREAD

**Issue by evfly** [rwv/chinese-dos-games#86]
**bug 描述**
系统卡在“read system config..."这一步.

**如何重现**
运行 红楼梦 十二金钗

**预期情况**
你预期的正常情况

**截图**
![capture](https://user-images.githubusercontent.com/44331564/47262749-2704d580-d523-11e8-97cd-d3db08c0dfd4.PNG)

**Comment by rwv** [comment]
img 挂载问题 #79 
https://github.com/rwv/chinese-dos-games/blob/master/games.json#L5505

**Comment by rwv** [comment]
应该已经修复完成 #79
