### ISSUE TITLE
剑侠情缘打不开

### ISSUE THREAD

**Issue by hsuhy** [rwv/chinese-dos-games#87]
**bug 描述**
bug 的描述
直接点击剑侠情缘，让插入第二张碟，
**如何重现**
如何重现这个 bug
直接点击剑侠情缘，只管按空格就一路退出到dos
**预期情况**
你预期的正常情况
应该打开游戏界面
**截图**
bug 的截图

**系统环境**
操作系统：win10
浏览器：chrome
游戏：剑侠情缘

**Comment by rwv** [comment]
应该已经修复完成 #79

**Comment by Marko8902** [comment]
同样的bug又出现了
