### ISSUE TITLE
《古文明霸王传》打不开

### ISSUE THREAD

**Issue by phoenixlhs** [rwv/chinese-dos-games#88]
**bug 描述**
《古文明霸王传》打不开，提示找不到光碟

**如何重现**
正常打开就能看到

**预期情况**
正常进入游戏

**截图**
暂无

**系统环境**
操作系统：Win7 64bit
浏览器：360极速浏览器9.5
游戏：《古文明霸王传》

**Comment by rwv** [comment]
fixed
