### ISSUE TITLE
游戏的下载问题

### ISSUE THREAD

**Issue by Doracoin** [rwv/chinese-dos-games#89]
**要求的功能**

游戏的下载功能：

我是在我的vps上运行的，硬盘剩余20G直接塞满了，所以这个游戏的下载形式可不可以由‘一键下载全部’改为‘列表选取’形式？

我的设想是运行`app.py`，先读取`game.json`文件，然后将目前整合的游戏信息通过web服务以列表形式展现出来（这个列表可以和现有列表独立出来，或者显示一个'是否已下载(缓存到服务器)'的状态），使用者想玩哪款游戏就选择下载哪款（此处的下载指将游戏下载到服务所运行的机器上），这样也可以节省上游服务器的流量及带宽。

顺便问问，现在已经整理的游戏一共有多大体积了？我好给我的硬盘腾腾地方

**优先度**
* [ ] 高
* [ ] 中
* [x] 低

**Comment by rwv** [comment]
一共 36G 的大小，web服务以列表形式展现出来估计短期内不会实现，优先级较低，您可以修改 `download_data.py` 进行选择性下载。

**Comment by Doracoin** [comment]
感谢回复，有时间我会自己改一改

**Comment by AsimovGod** [comment]
> 
> 
> 一共 36G 的大小，web服务以列表形式展现出来估计短期内不会实现，优先级较低，您可以修改 `download_data.py` 进行选择性下载。

想问一下，现在所有游戏大概多大，个人硬盘有50g

**Comment by rwv** [comment]
> > 一共 36G 的大小，web服务以列表形式展现出来估计短期内不会实现，优先级较低，您可以修改 `download_data.py` 进行选择性下载。
> 
> 想问一下，现在所有游戏大概多大，个人硬盘有50g

目前仍为这么大
