### ISSUE TITLE
江南才子唐伯虎

### ISSUE THREAD

**Issue by CoderKwong** [rwv/chinese-dos-games#9]
**游戏简体中文名：江南才子唐伯虎
**游戏繁体中文名：**
**游戏英文名：**
**游戏发行年份：1999
**游戏下载地址（可选）：http://small.bxamp.com/small/jiangnancztbh.rar
**游戏封面图地址（可选）：**
**其他（如键位、秘籍、链接等等）（可选）：**

**Comment by rwv** [comment]
@CoderKwong https://dos.zczc.cz/games/江南才子唐伯虎/

**Comment by abcfy2** [comment]
这游戏真是童年回忆，不过怎么敌方一方大招就特别卡？

**Comment by abcfy2** [comment]
我发现了，这游戏在firefox下运行速度还行，还算是流畅，在chrome下运行就跟ppt似的，尤其是只要一开大，卡帧特别严重。不知道是模拟器的问题还是chrome的设置问题

**Comment by rwv** [comment]
@abcfy2 现在既有说 Firefox 特别卡的也有说 Chrome 特别卡的，需要等较空闲的时候才能研究一下。
