### ISSUE TITLE
英雄传说4无法运行

### ISSUE THREAD

**Issue by wolvesky** [rwv/chinese-dos-games#91]
**bug 描述**
cannot find CD-ROM
Program removed

**如何重现**
运行游戏

**预期情况**
正常进入游戏

**截图**
bug 的截图

**系统环境**
操作系统：Windows10
浏览器：Chrome
游戏：英雄传说4

**Comment by rwv** [comment]
见 #79

**Comment by rwv** [comment]
应该已经修复完成 #79
