### ISSUE TITLE
侠客英雄传3无法运行，提示没有找到光驱，有什么办法吗？

### ISSUE THREAD

**Issue by gogo0508** [rwv/chinese-dos-games#92]
**bug 描述**
侠客英雄传3无法运行，提示没有找到光驱

**如何重现**
必现

**预期情况**
正常运行

**截图**
无

**系统环境**
操作系统：Windows 10
浏览器：Edge
游戏：侠客英雄传3

**Comment by rwv** [comment]
见 #79

**Comment by rwv** [comment]
查看配置文件后，跟 #79 无关系，具体无法运行原因未知。

**Comment by zgldh** [comment]
观察游戏zip包里的 `game.conf` 使用该配置在本地运行dosbox可以正常运行。
该配置文件最下面的脚本是关键：
```
mount c F:\game\xkyxz3\
IMGmount d F:\game\xkyxz3\cd\shk3_1.cue F:\game\xkyxz3\cd\shk3_2.cue -t iso
c:
shk3_
```

而网页版的dosbox我不知道能否支持引用该配置文件？

**Comment by rwv** [comment]
fixed, 需要使用 iso 而非 cue
