### ISSUE TITLE
命令与征服卡在启动界面

### ISSUE THREAD

**Issue by snakeliwei** [rwv/chinese-dos-games#93]
**bug 描述**
bug 的描述

**如何重现**
如何重现这个 bug

**预期情况**
你预期的正常情况

**截图**
bug 的截图

**系统环境**
操作系统：
浏览器：
游戏：

**Comment by rwv** [comment]
#79

**Comment by rwv** [comment]
查看配置文件后，跟 #79 无关系，具体无法运行原因未知。

**Comment by rwv** [comment]
fixed
